Repository Chandrakant0110/add-projects-get-pr-merged, pull requests merged in 2024-10, with the labels that each got.

#1 Add new web project user management
  web/redux-user-management-vite-js/.gitignore
  web/redux-user-management-vite-js/README.md
  web/redux-user-management-vite-js/eslint.config.js
  web/redux-user-management-vite-js/index.html
  web/redux-user-management-vite-js/package-lock.json
  web/redux-user-management-vite-js/package.json
  web/redux-user-management-vite-js/postcss.config.js
  web/redux-user-management-vite-js/public/vite.svg
  web/redux-user-management-vite-js/src/App.jsx
  web/redux-user-management-vite-js/src/assets/react.svg
  web/redux-user-management-vite-js/src/components/AddUser.jsx
  web/redux-user-management-vite-js/src/components/EditUser.jsx
  web/redux-user-management-vite-js/src/components/Userlist.jsx
  web/redux-user-management-vite-js/src/features/store.jsx
  web/redux-user-management-vite-js/src/features/userSlice.jsx
  web/redux-user-management-vite-js/src/index.css
  web/redux-user-management-vite-js/src/main.jsx
  web/redux-user-management-vite-js/src/test/App.test.jsx
  web/redux-user-management-vite-js/src/test/Slice.test.jsx
  web/redux-user-management-vite-js/src/test/UserList.test.jsx
  web/redux-user-management-vite-js/tailwind.config.js
  web/redux-user-management-vite-js/vite.config.js
  web/redux-user-management-vite-js/vitest.config.js
Labels: good first issue, hacktiberfest-2024, hacktoberfest-accepted

#2 Add files via upload
  CONTRIBUTING.md
  web/ecommerce/client/README.md
  web/ecommerce/client/index.html
  web/ecommerce/client/package-lock.json
  web/ecommerce/client/package.json
  web/ecommerce/client/postcss.config.js
  web/ecommerce/client/src/App.jsx
  web/ecommerce/client/src/assets/icons/cart-outline.svg
  web/ecommerce/client/src/axios.jsx
  web/ecommerce/client/src/components/Buttons.jsx
  web/ecommerce/client/src/components/Card.jsx
  web/ecommerce/client/src/components/Card.module.css
  web/ecommerce/client/src/components/CardsList.jsx
  web/ecommerce/client/src/components/Navbar.jsx
  web/ecommerce/client/src/components/Navbar.module.css
  web/ecommerce/client/src/index.css
  web/ecommerce/client/src/main.jsx
  web/ecommerce/client/src/pages/Cart.jsx
  web/ecommerce/client/src/pages/Contact.jsx
  web/ecommerce/client/src/pages/Home.jsx
  web/ecommerce/client/src/pages/Login.jsx
  web/ecommerce/client/src/pages/MyProfile.jsx
  web/ecommerce/client/src/pages/NoPage.jsx
  web/ecommerce/client/src/pages/Orders.jsx
  web/ecommerce/client/src/pages/SignUp.jsx
  web/ecommerce/client/tailwind.config.js
  web/ecommerce/client/vite.config.js
  web/ecommerce/server/connect.js
  web/ecommerce/server/controllers/staticController.js
  web/ecommerce/server/controllers/userController.js
  web/ecommerce/server/index.js
  web/ecommerce/server/middlewares/auth.js
  web/ecommerce/server/models/productsModel.js
  web/ecommerce/server/models/userModel.js
  web/ecommerce/server/package-lock.json
  web/ecommerce/server/package.json
  web/ecommerce/server/routes/staticRoute.js
  web/ecommerce/server/routes/userRoute.js
  web/ecommerce/server/service/auth.js
Labels: good first issue, hacktoberfest-2024, HACKTOBERFEST-ACCEPTED, hacktoberfest

#3 Added AuthorationAndAuthantication using express js
  CONTRIBUTING.md
  web/AuthorationAndAuthantication/connect.js
  web/AuthorationAndAuthantication/controllers/static.js
  web/AuthorationAndAuthantication/controllers/url.js
  web/AuthorationAndAuthantication/controllers/user.js
  web/AuthorationAndAuthantication/index.js
  web/AuthorationAndAuthantication/middleware/auth.js
  web/AuthorationAndAuthantication/models/url.js
  web/AuthorationAndAuthantication/models/user.js
  web/AuthorationAndAuthantication/package-lock.json
  web/AuthorationAndAuthantication/package.json
  web/AuthorationAndAuthantication/routes/staticRouter.js
  web/AuthorationAndAuthantication/routes/url.js
  web/AuthorationAndAuthantication/routes/user.js
  web/AuthorationAndAuthantication/service/auth.js
  web/AuthorationAndAuthantication/views/home.ejs
  web/AuthorationAndAuthantication/views/login.ejs
  web/AuthorationAndAuthantication/views/signup.ejs
Labels: hacktoberfest-2024, HACKTOBERFEST-ACCEPTED, hacktoberfest

#6 cloudinary-multer mern project
  CONTRIBUTING.md
  web/cloudinary-multer/backend/package-lock.json
  web/cloudinary-multer/backend/package.json
  web/cloudinary-multer/backend/src/controller/routeUpload.js
  web/cloudinary-multer/backend/src/index.js
  web/cloudinary-multer/backend/src/middleware/multer.js
  web/cloudinary-multer/backend/src/utils/cloudinary.js
  web/cloudinary-multer/frontend/README.md
  web/cloudinary-multer/frontend/eslint.config.js
  web/cloudinary-multer/frontend/index.html
  web/cloudinary-multer/frontend/package-lock.json
  web/cloudinary-multer/frontend/package.json
  web/cloudinary-multer/frontend/public/vite.svg
  web/cloudinary-multer/frontend/src/App.jsx
  web/cloudinary-multer/frontend/src/index.css
  web/cloudinary-multer/frontend/src/main.jsx
  web/cloudinary-multer/frontend/vite.config.js
Labels: hacktoberfest-2024, HACKTOBERFEST-ACCEPTED, hacktoberfest
